const friends = [
  {
    id: 1,
    name: "Alice Johnson",
    lastMsg: "See you soon!",
    lastMsgTime: "10:15 AM",
    msgSeen: true,
  },
  {
    id: 2,
    name: "Bob Smith",
    lastMsg: "Got it, thanks!",
    lastMsgTime: "09:50 AM",
    profilePic: "https://randomuser.me/api/portraits/men/2.jpg",
    msgSeen: false,
  },
  {
    id: 3,
    name: "Charlie Lee",
    lastMsg: "Let's catch up later.",
    lastMsgTime: "Yesterday",
    profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
    msgSeen: true,
  },
  {
    id: 4,
    name: "Diana Prince",
    lastMsg: "Happy Birthday!",
    lastMsgTime: "Yesterday",
    profilePic: "https://randomuser.me/api/portraits/women/4.jpg",
    msgSeen: true,
  },
  {
    id: 5,
    name: "Ethan Hunt",
    lastMsg: "Mission accomplished.",
    lastMsgTime: "08:30 AM",
    profilePic: "https://randomuser.me/api/portraits/men/5.jpg",
    msgSeen: false,
  },
  {
    id: 6,
    name: "Fiona Gallagher",
    lastMsg: "Call me when you're free.",
    lastMsgTime: "07:45 AM",
    profilePic: "https://randomuser.me/api/portraits/women/6.jpg",
    msgSeen: true,
  },
  {
    id: 7,
    name: "George Miller",
    lastMsg: "Thanks for the update.",
    lastMsgTime: "Monday",
    profilePic: "https://randomuser.me/api/portraits/men/7.jpg",
    msgSeen: false,
  },
  {
    id: 8,
    name: "Hannah Brown",
    lastMsg: "See you at the event.",
    lastMsgTime: "Sunday",
    profilePic: "https://randomuser.me/api/portraits/women/8.jpg",
    msgSeen: true,
  },
  {
    id: 9,
    name: "Ian Curtis",
    lastMsg: "I'll be late.",
    lastMsgTime: "Saturday",
    profilePic: "https://randomuser.me/api/portraits/men/9.jpg",
    msgSeen: false,
  },
  {
    id: 10,
    name: "Julia Roberts",
    lastMsg: "Great job!",
    lastMsgTime: "Friday",
    profilePic: "https://randomuser.me/api/portraits/women/10.jpg",
    msgSeen: true,
  },
];

export default friends;